//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRestaurantSiglo21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANCOMOVIMIENTO
    {
        public decimal IDMOVIMIENTOBANCARIO { get; set; }
        public Nullable<System.DateTime> FECHAMOVBANCARIO { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public decimal IDENTIDADBANCARIA { get; set; }
        public decimal IDEGRESO { get; set; }
        public decimal IDINGRESO { get; set; }
        public decimal IDTIPOCUENTA { get; set; }
    
        public virtual INGRESO INGRESO { get; set; }
        public virtual EGRESO EGRESO { get; set; }
        public virtual ENTIDADBANCARIA ENTIDADBANCARIA { get; set; }
        public virtual TIPOMOVBANCO TIPOMOVBANCO { get; set; }
    }
}
