//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRestaurantSiglo21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJAOPERACION
    {
        public int IDCAJAOPERACION { get; set; }
        public Nullable<int> MONTOOPERACION { get; set; }
        public Nullable<System.DateTime> FECHAINICIOCAJA { get; set; }
        public Nullable<System.DateTime> FECHACIERRECAJA { get; set; }
        public byte IDCAJAESTADO { get; set; }
        public int IDPERSONA { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual CAJAESTADO CAJAESTADO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
