
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppRestaurantSiglo21.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CAJAOPERACION
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CAJAOPERACION()
    {

        this.INGRESO = new HashSet<INGRESO>();

    }


    public decimal IDCAJAOPERACION { get; set; }

    public Nullable<System.DateTime> FECHAAPERTURA { get; set; }

    public Nullable<decimal> MONTOAPERTURA { get; set; }

    public decimal IDCAJAESTADO { get; set; }

    public decimal IDUSUARIO { get; set; }



    public virtual CAJAESTADO CAJAESTADO { get; set; }

    public virtual USUARIO USUARIO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<INGRESO> INGRESO { get; set; }

}

}
