
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppRestaurantSiglo21.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CLIENTE
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CLIENTE()
    {

        this.DOCUMENTOPAGO = new HashSet<DOCUMENTOPAGO>();

        this.PERSONA1 = new HashSet<PERSONA>();

        this.RESERVA = new HashSet<RESERVA>();

    }


        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        public decimal IDCLIENTE { get; set; }

    public Nullable<System.DateTime> FECHAINGRESO { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0}")]
        public decimal RUTPERSONA { get; set; }

    public string NOMBRE { get; set; }

    public string APELLIDOPATERNO { get; set; }

    public string APELLIDOMATERNO { get; set; }

    public string DIRECCION { get; set; }

    public string FONO { get; set; }

    public string EMAIL { get; set; }



    public virtual PERSONA PERSONA { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DOCUMENTOPAGO> DOCUMENTOPAGO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PERSONA> PERSONA1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RESERVA> RESERVA { get; set; }

}

}
