//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRestaurantSiglo21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLACOCINA
    {
        public int IDCOLACOCINA { get; set; }
        public Nullable<System.DateTime> HORACREACION { get; set; }
        public Nullable<System.DateTime> HORAACTUAL { get; set; }
        public Nullable<System.DateTime> HORAENTREGA { get; set; }
        public Nullable<int> NROPEDIDO { get; set; }
        public Nullable<byte> ESTADOPEDIDO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<short> DIFICULTADPREP { get; set; }
        public Nullable<short> TIEMPOPREP { get; set; }
    }
}
