
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppRestaurantSiglo21.Models
{

using System;
    using System.Collections.Generic;
    
public partial class COMPRA
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public COMPRA()
    {

        this.EGRESO = new HashSet<EGRESO>();

    }


    public decimal IDCOMPRA { get; set; }

    public Nullable<System.DateTime> FECHACOMPRA { get; set; }

    public decimal IDPEDIDO { get; set; }

    public decimal IDUSUARIO { get; set; }



    public virtual PEDIDO PEDIDO { get; set; }

    public virtual USUARIO USUARIO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EGRESO> EGRESO { get; set; }

}

}
