//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRestaurantSiglo21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEORDEN
    {
        public int IDDETALLEORDEN { get; set; }
        public Nullable<short> CANTIDAD { get; set; }
        public int IDORDEN { get; set; }
        public int IDPRODUCTO { get; set; }
        public Nullable<int> PRECIOPROD { get; set; }
        public byte IDESTADO { get; set; }
        public Nullable<System.DateTime> HORADETORD { get; set; }
    
        public virtual ESTADOORDEN ESTADOORDEN { get; set; }
        public virtual ORDEN ORDEN { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
