
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppRestaurantSiglo21.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DOCUMENTOPAGO
{

    public decimal IDDOCUMENTOPAGO { get; set; }

    public decimal IDCLIENTE { get; set; }

    public Nullable<decimal> IDORDEN { get; set; }

    public Nullable<decimal> TOTAL { get; set; }

    public decimal IDDOCTPAGOTIPO { get; set; }

    public decimal IDMEDIOPAGO { get; set; }



    public virtual CLIENTE CLIENTE { get; set; }

    public virtual DOCTPAGOTIPO DOCTPAGOTIPO { get; set; }

    public virtual MEDIOPAGO MEDIOPAGO { get; set; }

}

}
