//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRestaurantSiglo21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOPAGO
    {
        public byte IDDOCTOPAGO { get; set; }
        public Nullable<decimal> IDORDEN { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<int> IDPERSONA { get; set; }
        public Nullable<byte> IDDOCTPAGOTIPO { get; set; }
        public Nullable<byte> IDMEDIOPAGO { get; set; }
        public Nullable<int> PROPINA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual DOCTPAGOTIPO DOCTPAGOTIPO { get; set; }
        public virtual MEDIOPAGO MEDIOPAGO { get; set; }
    }
}
