
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppRestaurantSiglo21.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EGRESO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EGRESO()
    {

        this.BANCOMOVIMIENTO = new HashSet<BANCOMOVIMIENTO>();

    }


    public decimal IDEGRESO { get; set; }

    public Nullable<decimal> MONTO { get; set; }

    public string DESCMOVIMIENTO { get; set; }

    public Nullable<System.DateTime> FECHAMOVIMIENTO { get; set; }

    public decimal IDCOMPRA { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BANCOMOVIMIENTO> BANCOMOVIMIENTO { get; set; }

    public virtual COMPRA COMPRA { get; set; }

}

}
