
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppRestaurantSiglo21.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ENTIDADBANCARIA
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ENTIDADBANCARIA()
    {

        this.BANCOMOVIMIENTO = new HashSet<BANCOMOVIMIENTO>();

    }


    public decimal IDENTIDADBANCARIA { get; set; }

    public string DESCBANCO { get; set; }

    public decimal IDTIPOCUENTA { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BANCOMOVIMIENTO> BANCOMOVIMIENTO { get; set; }

    public virtual TIPOCUENTA TIPOCUENTA { get; set; }

}

}
