//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRestaurantSiglo21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGRESO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INGRESO()
        {
            this.BANCOMOVIMIENTO = new HashSet<BANCOMOVIMIENTO>();
        }
    
        public decimal IDINGRESO { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public string DESCINGRESO { get; set; }
        public Nullable<System.DateTime> FECHAMOVIMIENTO { get; set; }
        public decimal IDCAJAOPERACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANCOMOVIMIENTO> BANCOMOVIMIENTO { get; set; }
        public virtual CAJAOPERACION CAJAOPERACION { get; set; }
    }
}
