
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppRestaurantSiglo21.Models
{

using System;
    using System.Collections.Generic;
    
public partial class INSUMOSTOCK
{

    public decimal IDPRODUCTOENBODEGA { get; set; }

    public Nullable<decimal> STOCKACTUAL { get; set; }

    public Nullable<decimal> STOCKMINIMO { get; set; }

    public decimal IDINSUMO { get; set; }



    public virtual INSUMO INSUMO { get; set; }

}

}
