
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppRestaurantSiglo21.Models
{

using System;
    using System.Collections.Generic;
    
public partial class INSUMO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public INSUMO()
    {

        this.BODEGAMOVIMIENTO = new HashSet<BODEGAMOVIMIENTO>();

        this.INSUMOSTOCK = new HashSet<INSUMOSTOCK>();

        this.PEDIDOINSUMO = new HashSet<PEDIDOINSUMO>();

        this.PROVEEDOR = new HashSet<PROVEEDOR>();

    }


    public decimal IDINSUMO { get; set; }

    public string DESCINSUMO { get; set; }

    public Nullable<decimal> PRECIOINSUMO { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BODEGAMOVIMIENTO> BODEGAMOVIMIENTO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<INSUMOSTOCK> INSUMOSTOCK { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PEDIDOINSUMO> PEDIDOINSUMO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PROVEEDOR> PROVEEDOR { get; set; }

}

}
