//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRestaurantSiglo21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDIOPAGOTX
    {
        public decimal IDMEDIOPAGOTX { get; set; }
        public string DESCMEDIOPAGO { get; set; }
        public Nullable<decimal> RUT { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public decimal IDMEDIOPAGO { get; set; }
    
        public virtual MEDIOPAGO MEDIOPAGO { get; set; }
    }
}
