
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppRestaurantSiglo21.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MESA
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MESA()
    {

        this.RESERVA = new HashSet<RESERVA>();

    }


    public decimal IDMESA { get; set; }

    public string DESCMESA { get; set; }

    public Nullable<decimal> CAPACIDAD { get; set; }

    public decimal IDLOCAL { get; set; }

    public decimal IDESTADOMESA { get; set; }



    public virtual ESTADOMESA ESTADOMESA { get; set; }

    public virtual RESTAURANT RESTAURANT { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RESERVA> RESERVA { get; set; }

}

}
