//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRestaurantSiglo21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEN()
        {
            this.DETALLEORDEN = new HashSet<DETALLEORDEN>();
        }
    
        public int IDORDEN { get; set; }
        public Nullable<System.DateTime> FECHAORDEN { get; set; }
        public Nullable<int> IDRESERVA { get; set; }
        public byte IDESTADO { get; set; }
        public Nullable<short> IDEMPTURNO { get; set; }
        public short IDMESA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEORDEN> DETALLEORDEN { get; set; }
        public virtual EMPLEADOTURNO EMPLEADOTURNO { get; set; }
        public virtual ESTADOORDEN ESTADOORDEN { get; set; }
        public virtual MESA MESA { get; set; }
        public virtual RESERVA RESERVA { get; set; }
    }
}
