
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppRestaurantSiglo21.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ORDEN
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ORDEN()
    {

        this.DETALLEORDEN = new HashSet<DETALLEORDEN>();

    }


    public decimal IDORDEN { get; set; }

    public Nullable<System.DateTime> FECHAORDEN { get; set; }

    public decimal IDEMPTURNO { get; set; }

    public decimal IDRESRVA { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DETALLEORDEN> DETALLEORDEN { get; set; }

    public virtual EMPLEADOTURNO EMPLEADOTURNO { get; set; }

    public virtual RESERVA RESERVA { get; set; }

}

}
