
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppRestaurantSiglo21.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PEDIDO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PEDIDO()
    {

        this.COMPRA = new HashSet<COMPRA>();

        this.PEDIDOINSUMO = new HashSet<PEDIDOINSUMO>();

    }


    public decimal IDPEDIDO { get; set; }

    public string FECHAPEDIDO { get; set; }

    public decimal IDUSUARIO { get; set; }

    public decimal IDPROVEEDOR { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<COMPRA> COMPRA { get; set; }

    public virtual PROVEEDOR PROVEEDOR { get; set; }

    public virtual USUARIO USUARIO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PEDIDOINSUMO> PEDIDOINSUMO { get; set; }

}

}
