//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRestaurantSiglo21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODPREPARACION
    {
        public int IDPRODPREPAR { get; set; }
        public decimal TIEMPOPREPARACION { get; set; }
        public int IDPRODUCTO { get; set; }
        public byte IDTIPOPREP { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual TIPOPREPARACION TIPOPREPARACION { get; set; }
    }
}
