//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRestaurantSiglo21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.DETALLEORDEN = new HashSet<DETALLEORDEN>();
            this.PRODPREPARACION = new HashSet<PRODPREPARACION>();
        }
    
        public int IDPRODUCTO { get; set; }
        public string DESCPRODUCTO { get; set; }
        public Nullable<decimal> PRECIOPRODUCTO { get; set; }
        public byte IDESTPRODUCTO { get; set; }
        public byte IDTIPOPRODUCTO { get; set; }
        public Nullable<short> IDRECPRODUCTO { get; set; }
        public string FOTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEORDEN> DETALLEORDEN { get; set; }
        public virtual ESTADOPRODUCTO ESTADOPRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODPREPARACION> PRODPREPARACION { get; set; }
        public virtual RECETAPRODUCTO RECETAPRODUCTO { get; set; }
        public virtual TIPOPRODUCTO TIPOPRODUCTO { get; set; }
    }
}
