//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRestaurantSiglo21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public short IDPROVEEDOR { get; set; }
        public int RUTPROVEEDOR { get; set; }
        public string DVPROVEEDOR { get; set; }
        public string NOMPROV { get; set; }
        public string FONO { get; set; }
        public byte IDESTPROVEEDOR { get; set; }
        public string DESCTIPOPROVEEDOR { get; set; }
    
        public virtual ESTADOPROVEEDOR ESTADOPROVEEDOR { get; set; }
    }
}
