//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRestaurantSiglo21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVA()
        {
            this.ORDEN = new HashSet<ORDEN>();
        }
    
        public decimal IDRESRVA { get; set; }
        public Nullable<System.DateTime> FECHARESERVA { get; set; }
        public Nullable<decimal> CANTIDADCLIENTE { get; set; }
        public decimal IDESTADORESRVA { get; set; }
        public decimal IDMESA { get; set; }
        public decimal IDCLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ESTADORESERVA ESTADORESERVA { get; set; }
        public virtual MESA MESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN> ORDEN { get; set; }
    }
}
