//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRestaurantSiglo21.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestaurantEntities : DbContext
    {
        public RestaurantEntities()
            : base("name=RestaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANCOMOVIMIENTO> BANCOMOVIMIENTO { get; set; }
        public virtual DbSet<BODEGAMOVIMIENTO> BODEGAMOVIMIENTO { get; set; }
        public virtual DbSet<CAJAESTADO> CAJAESTADO { get; set; }
        public virtual DbSet<CAJAOPERACION> CAJAOPERACION { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<COMPRA> COMPRA { get; set; }
        public virtual DbSet<DETALLEORDEN> DETALLEORDEN { get; set; }
        public virtual DbSet<DOCTPAGOTIPO> DOCTPAGOTIPO { get; set; }
        public virtual DbSet<DOCUMENTOPAGO> DOCUMENTOPAGO { get; set; }
        public virtual DbSet<EGRESO> EGRESO { get; set; }
        public virtual DbSet<EMPLEADOTURNO> EMPLEADOTURNO { get; set; }
        public virtual DbSet<ENTIDADBANCARIA> ENTIDADBANCARIA { get; set; }
        public virtual DbSet<ESTADOMESA> ESTADOMESA { get; set; }
        public virtual DbSet<ESTADOORDEN> ESTADOORDEN { get; set; }
        public virtual DbSet<ESTADOPRODUCTO> ESTADOPRODUCTO { get; set; }
        public virtual DbSet<ESTADORESERVA> ESTADORESERVA { get; set; }
        public virtual DbSet<FUNCIONALIDAD> FUNCIONALIDAD { get; set; }
        public virtual DbSet<INGRESO> INGRESO { get; set; }
        public virtual DbSet<INSUMO> INSUMO { get; set; }
        public virtual DbSet<INSUMOSTOCK> INSUMOSTOCK { get; set; }
        public virtual DbSet<MEDIOPAGO> MEDIOPAGO { get; set; }
        public virtual DbSet<MEDIOPAGOTX> MEDIOPAGOTX { get; set; }
        public virtual DbSet<MESA> MESA { get; set; }
        public virtual DbSet<ORDEN> ORDEN { get; set; }
        public virtual DbSet<PEDIDO> PEDIDO { get; set; }
        public virtual DbSet<PEDIDOINSUMO> PEDIDOINSUMO { get; set; }
        public virtual DbSet<PERMISOS> PERMISOS { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PRODUCTOPREPARACION> PRODUCTOPREPARACION { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<RECETAPRODUCTO> RECETAPRODUCTO { get; set; }
        public virtual DbSet<RESERVA> RESERVA { get; set; }
        public virtual DbSet<RESTAURANT> RESTAURANT { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<TIPOCUENTA> TIPOCUENTA { get; set; }
        public virtual DbSet<TIPOMOVBANCO> TIPOMOVBANCO { get; set; }
        public virtual DbSet<TIPOMOVBODEGA> TIPOMOVBODEGA { get; set; }
        public virtual DbSet<TIPOPREPARACION> TIPOPREPARACION { get; set; }
        public virtual DbSet<TIPOPRODUCTO> TIPOPRODUCTO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<USUARIOROL> USUARIOROL { get; set; }
    
        public virtual int SP_REGISTRARCLIENTE(Nullable<decimal> pE_RUT, string pE_NOMB, string pE_APEP, string pE_APEM, string pE_DIRE, string pE_FONO, string pE_EMAIL, Nullable<decimal> pE_IDCLI)
        {
            var pE_RUTParameter = pE_RUT.HasValue ?
                new ObjectParameter("PE_RUT", pE_RUT) :
                new ObjectParameter("PE_RUT", typeof(decimal));
    
            var pE_NOMBParameter = pE_NOMB != null ?
                new ObjectParameter("PE_NOMB", pE_NOMB) :
                new ObjectParameter("PE_NOMB", typeof(string));
    
            var pE_APEPParameter = pE_APEP != null ?
                new ObjectParameter("PE_APEP", pE_APEP) :
                new ObjectParameter("PE_APEP", typeof(string));
    
            var pE_APEMParameter = pE_APEM != null ?
                new ObjectParameter("PE_APEM", pE_APEM) :
                new ObjectParameter("PE_APEM", typeof(string));
    
            var pE_DIREParameter = pE_DIRE != null ?
                new ObjectParameter("PE_DIRE", pE_DIRE) :
                new ObjectParameter("PE_DIRE", typeof(string));
    
            var pE_FONOParameter = pE_FONO != null ?
                new ObjectParameter("PE_FONO", pE_FONO) :
                new ObjectParameter("PE_FONO", typeof(string));
    
            var pE_EMAILParameter = pE_EMAIL != null ?
                new ObjectParameter("PE_EMAIL", pE_EMAIL) :
                new ObjectParameter("PE_EMAIL", typeof(string));
    
            var pE_IDCLIParameter = pE_IDCLI.HasValue ?
                new ObjectParameter("PE_IDCLI", pE_IDCLI) :
                new ObjectParameter("PE_IDCLI", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REGISTRARCLIENTE", pE_RUTParameter, pE_NOMBParameter, pE_APEPParameter, pE_APEMParameter, pE_DIREParameter, pE_FONOParameter, pE_EMAILParameter, pE_IDCLIParameter);
        }
    }
}
