
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AppRestaurantSiglo21.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TIPOMOVBODEGA
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TIPOMOVBODEGA()
    {

        this.BODEGAMOVIMIENTO = new HashSet<BODEGAMOVIMIENTO>();

    }


    public decimal IDTIPOMOVIMIENTO { get; set; }

    public string DESCTIPOMOVIMIENTO { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BODEGAMOVIMIENTO> BODEGAMOVIMIENTO { get; set; }

}

}
