//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRestaurantSiglo21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOROL
    {
        public decimal IDUSUARIOROL { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICACION { get; set; }
        public decimal ROL_IDROL { get; set; }
        public decimal IDUSUARIO { get; set; }
    
        public virtual ROL ROL { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
